### ISSUE TITLE
Prevent all PR builds from being written to the "merge" url

### ISSUE THREAD

**Issue by noce2cicd** [math-dojo/single-page-web-app#37]
At present, all PR builds are deployed on the `mathdojouibuildmerge` account which means that only one PR's deployed code can be viewed at a time. The purpose of this is to solve that. The solution used in the user-account-service can be employed here:

https://github.com/math-dojo/user-account-service/blob/8b8d4d112a3929608ecc7204d4cc4ec3854b2a28/azure-pipelines.yml#L38

- [x] Each PR and its built code can be found on a separate Azure Storage Account

**Comment by noce2** [comment]
This was resolved in commit: 5252a0ba739926838f12d9ce8b14d93f6718f687
